task: wug
dataset_path: json
dataset_name: null
dataset_kwargs:
  data_files: /home/xlxw/projects/CxGLearner/CxGLM/wugtest/tasks/wug/wug_data.json
validation_split: train
output_type: loglikelihood_with_multi_choices
doc_to_text: "{{text.split(' ')[:-1]|join(' ')}} "
doc_to_target: "{{text.split(' ')[-1].split('-')}}"
should_decontaminate: true
doc_to_decontamination_query: "{{text}}"
metric_list:
  - metric: perplexity
    aggregation: perplexity
    higher_is_better: false
  - metric: acc
    aggregation: mean
    higher_is_better: true
